---
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing Packer..."
      - curl -qsL -o packer.zip https://releases.hashicorp.com/packer/1.4.5/packer_1.4.5_linux_amd64.zip && unzip packer.zip
      - echo "Validating Packer Template [packer.json]"
      - ./packer validate packer.json
  build:
    commands:
      - echo "Building Packer Template [packer.json]"
      - PACKER_LOG=1 ./packer build packer.json
  post_build:
    commands:
      - echo "Completed Packer Build at `date`"
